services:
  php:
    build:
        context: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./custom-apache.conf:/etc/apache2/conf-available/custom-apache.conf
    command: >
      /bin/bash -c "a2enconf custom-apache && apache2-foreground"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
